---
- hosts: localhost
  user: ansible
  become: yes
  become_method: sudo
  vars:
    tomcat_base: /opt/apache-tomcat-9.0.11
    tomcat_port: 8080
    tomcat_ssl_port: 8443

    domains:
      - { domain_name: abcapi }
      - { domain_name: xyzapi }

  tasks:
    
  - name: Make sure that we can connect to the machine
    ping:

  - name: include extra prameters
    include_vars: vars/tomcat-users-password.yml

  - name: Install java-1.8.0-openjdk
    yum: name=java-1.8.0-openjdk state=present

  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat createhome=yes
    become: true

  - name: Download tomcat tar to /tmp dir
    get_url: url=http://mirrors.fibergrid.in/apache/tomcat/tomcat-9/v9.0.12/bin/apache-tomcat-9.0.12.tar.gz  dest=/tmp/apache-tomcat-9.0.11.tar.gz

  - name: setup systemd file for tomcat service
    template: src=files/tomcat.service  dest=/etc/systemd/system/tomcat.service mode=644 

  - name: Extract tomcat to target directory
    command: tar zxvf /tmp/apache-tomcat-9.0.11.tar.gz -C /opt creates={{tomcat_base}}
   
  - name: set correct ownership for tomcat installation directory
    file: path={{tomcat_base}} owner=tomcat group=tomcat state=directory recurse=yes

  - name: Configure Tomcat server Configuration
    template: src=templates/server.xml.j2  dest={{tomcat_base}}/conf/server.xml
    notify: restart tomcat

  - name: Configure Keytore configuration
    copy: src=files/crashmeal.com.jks dest={{tomcat_base}}/conf/crashmeal.com.jks owner=tomcat group=tomcat 

  - name: Configure Tomcat users
    template: src=templates/tomcat-users.xml.j2 dest={{tomcat_base}}/conf/tomcat-users.xml
    notify: restart tomcat

  - name: Enable Host Manager Access
    template: src=templates/context.xml.host  dest={{tomcat_base}}/webapps/host-manager/META-INF
    notify: restart tomcat

  - name: Enable Manager Access
    template: src=templates/context.xml.manager dest={{tomcat_base}}/webapps/manager/META-INF/context.xml
    notify: restart tomcat

  - name: Enable tomcat port under firewall
    firewalld: port={{tomcat_port}}/tcp zone=public permanent=true state=enabled immediate=yes

  - name: Enable tomcat secure port under firewall
    firewalld: port={{tomcat_ssl_port}}/tcp zone=public permanent=true state=enabled immediate=yes

  - name: create necessary log files for virtualhosts
    copy: content="" force=no dest={{tomcat_base}}/logs/{{item.domain_name}}_access_log.txt owner=tomcat group=tomcat mode=644
    with_items: 
      - "{{ domains }}"

  - name: Start Tomcat
    service: 
      name: tomcat
      state: started
  
  handlers: 
  - name: restart tomcat
    service: 
      name: tomcat
      state: restarted
